version: "3.6"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    ports:
      - "5601:5601"
    networks:
      - es-net

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.1.2"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./elastic_search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net
  nats:
    image: "nats-streaming:0.9.2"
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: "always"
    networks:
      - es-net
  postgres:
    image: "postgres"
    restart: "always"
    networks:
      - es-net
    volumes:
      - ./postgres/up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"
  meow:
    build: "."
    command: "meow-service"
    networks:
      - es-net
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_USER: "meower"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"
  query:
    build: "."
    command: "query-service"
    networks:
      - es-net
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "meower"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "meower"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    command: "pusher-service"
    networks:
      - es-net
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  nginx:
    image: nginx:latest
    networks:
      - es-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - "meow"
      - "query"
      - "pusher"

networks:
  es-net:
    driver: bridge